ezh/ezh/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('journal.urls'))
]

ezh/journal/urls.py
from django.urls import path

from . import views
app_name = 'journal'
urlpatterns = [
    path('', views.index, name='index'),
    path('add_mark/', views.add_mark, name='add_mark'),
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='register'),
    path('uid/', views.create_UID, name='uid'),
    path('school/roster/', views.school_roster, name='school_roster'),
    path('marks/', views.marks, name='marks'),
    path('<int:userid>/marks/', views.foreigner_marks, name='foreigner_marks'),
    path('profile/', views.profile, name='profile'),
    path('init/', views.initiate_test_data, name='init'),
    path('<int:userid>/profile/', views.foreigner_profile, name='foreigner_profile'),
    path('profile/edit/', views.profile_edit, name='profile_edit'),
    path('school/my_schedule/', views.my_schedule, name='my_schedule'),
    path('school/<int:class_n>/<str:class_a>/roster/', views.class_roster, name='class_roster'),
    path('school/<int:userid>/schedule/', views.foreigner_schedule, name='foreigner_schedule'),
    path('school/<int:class_n>/<str:class_a>/schedule/', views.class_schedule, name='class_schedule'),
    path('school/<int:class_n>/<str:class_a>/', views.class_info, name='class_info'),
    path('school/<int:class_n>/<str:class_a>/<int:lesson_id>', views.class_lesson_marks, name='class_lesson_marks'),
]

ezh/journal/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import datetime
import django.utils

class MyUser(AbstractUser):
    # Mutual fields
    type_user = models.IntegerField(default=0) # 0-Guest 1-Teacher 2-Student 3-Staff
    personal_code = models.CharField(max_length=128, default='')
    midname = models.CharField(max_length=128, default='')
    date_of_birth = models.DateField(auto_now_add=False, null=True)
    email = models.EmailField(max_length=128)
    telephone = models.CharField(max_length=128, default='')
    activated = models.BooleanField(default=False)
    # From teacher
    info_parents = models.CharField(max_length=228, default='')
    self_grades = models.ManyToManyField(to='Grade', related_name="self_grades_id")
    #all_lessons = models.ManyToManyField(to='Lesson_instance', related_name='subjects_id')
    #teaches = models.CharField(max_length=254, default='')
    # From student
    grade = models.ForeignKey(to='Grade', null=True, on_delete=models.SET_NULL, related_name='grade_id')
    # From staff
    staff_role = models.CharField(max_length=128, default='')
    schedule = models.ForeignKey(to='WeekSchedule', null=True, on_delete=models.SET_NULL, related_name='o_schedule')
    def activate(self):
        self.activated = True

    def show_self_grades(self):
        g = self.self_grades.all()
        mas = str()
        for i in range(len(g)):
            mas+= "<a href='../../school/" + str(g[i].grade_number) + '/' + str(g[i].grade_alpha) + "/'>" + str(g[i].grade_number) + str(g[i].grade_alpha) + '</a> '
        return mas

    def to_teach(self):
        all = Lesson_instance.objects.filter(lecturer=self)
        s = set()
        for i in all:
            s.add(i.name)
        return str(list(s)).replace('[', '').replace(']', '').replace("'", '')

    def full_name(self):
        return self.last_name + ' ' + self.first_name+' '+self.midname

class Grade(models.Model):
    grade_number = models.IntegerField(default=0)
    grade_alpha = models.CharField(max_length=1, default='')
    head = models.ForeignKey(to='MyUser', null=True, on_delete=models.SET_NULL, related_name='head_id')
    #elder = models.ForeignKey(to='MyUser', null=True, on_delete=models.SET_NULL, related_name='elder_student_id')
    roster = models.ManyToManyField(to='MyUser', related_name="roster")
    schedule = models.ForeignKey(to='WeekSchedule', null=True, on_delete=models.SET_NULL, related_name='schedule')

    def get_roster(self):
        r = self.roster.all()
        mas = []
        for i in r:
            mas.append(i)
        return mas

class Lesson(models.Model):
    name = models.CharField(max_length=128)


class Lesson_instance(models.Model):
    lesson = models.ForeignKey(to='Lesson', null=True, on_delete=models.SET_NULL, related_name='lesson_link')
    name = models.CharField(max_length=128, default='')
    lecturer = models.ForeignKey(to='MyUser', null=True, on_delete=models.SET_NULL, related_name='lecturer_id')
    grade_to_teach = models.ForeignKey(to='Grade', null=True, on_delete=models.SET_NULL,
                                       related_name='grade_to_teach_id')
    time = models.CharField(default='', max_length=4)
    additional_students = models.ManyToManyField(to='MyUser', related_name="additional_students")
    faculty = models.BooleanField(default=False)

    def get_lessons_names(self):
        l = Lesson_instance.objects.all()
        mas = []
        for i in l:
          mas.append(i.name)
        return set(mas)


    def get_additional_students(self):
        mas = []
        for i in self.additional_students.all():
            mas.append(i)

    def print_time(self):
        t = self.time
        r = t[:2] + ':' + t[2:]
        return r

'''
class Journal(models.Model):
    grade = models.ForeignKey(to='Grade', null=True, on_delete=models.SET_NULL, related_name='journal_of_grade')
    lesson = models.ForeignKey(to='Lesson_instance', null=True, on_delete=models.SET_NULL, related_name='journal_of_grade')
    days = models.ManyToManyField(to='Day', related_name="days_in_journal")

'''


class Journal(models.Model):
    to_user = models.ForeignKey(to='MyUser', null=True, on_delete=models.SET_NULL, related_name='journal_of_grade')
    lesson = models.ForeignKey(to='Lesson_instance', null=True, on_delete=models.SET_NULL, related_name='journal_of_grade')
    days = models.ManyToManyField(to='Day', related_name="days_in_journal")


class Day(models.Model):
    marks = models.ManyToManyField(to='Mark', related_name="roster")
    day = models.DateField(default=datetime.datetime.today().strftime('%Y-%m-%d'))
    # in_place = models.ManyToManyField(to='MyUser', related_name="roster_in_place")


class Mark(models.Model):
    # -1 if student is abscent
    value = models.IntegerField()
    day = models.DateField(default=datetime.datetime.today().strftime('%Y-%m-%d'))
    lesson = models.ForeignKey(to='Lesson_instance', null=True, on_delete=models.SET_NULL, related_name='mark_from_lesson')
    student = models.ForeignKey(to='MyUser', null=True, on_delete=models.SET_NULL, related_name='student')
    def get_days(stud):
        l = Mark.objects.filter(student = stud)
        mas = []
        for i in l:
          mas.append(i.day)
        return set(mas)



class DaySchedule(models.Model):
    day = models.IntegerField(default=0)
    # 1 - Monday, 2-Tuesday, 3-Wednesday, 4-Thursday, 5-Friday, 6-Saturday, 7-Sunday
    lessons = models.ManyToManyField(to='Lesson_instance', related_name='lessons_id')

    def my_lessons(self):
        l = []
        for i in self.lessons.all():
            l.append(i)
        return l
        
    def my_lessons_names(self):
        l = []
        for i in self.lessons.all():
            l.append(i.name)
        return l


class WeekSchedule(models.Model):
    all_days_schedules = models.ManyToManyField(to='DaySchedule', related_name='all_days_schedule')

    def days(self):
        l = []
        for i in self.all_days_schedules.all():
            l.append(i)
        return l

ezh/journal/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
import django.contrib.auth
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.shortcuts import render
from .models import *
from django.contrib.auth.hashers import *
import hashlib
import datetime
from django.shortcuts import redirect
from django.http import HttpResponse, HttpResponseNotFound
import smtplib


@login_required(login_url='/login')
def school_roster(request):
    context = dict()
    context['teachers'] = MyUser.objects.filter(type_user=1)
    context['students'] = MyUser.objects.filter(type_user=2)
    context['staff'] = MyUser.objects.filter(type_user=3)
    return render(request, 'school_roster.html', context)


def add_mark(request):
    context = dict()
    if request.method == 'POST':
        value = request.POST['mark']
        lesson_id = request.POST['lesson_id']
        student_id = request.POST['student_id']
        mark = Mark(value=value, lesson=Lesson_instance.objects.filter(id=lesson_id)[0],
                    student=MyUser.objects.filter(id=student_id)[0])
        mark.save()

        current_date = datetime.datetime.today().strftime('%Y-%m-%d')
        day = Day.objects.filter(day=current_date)
        if len(day) == 0 or day is None:
            day = Day()
            day.save()
            day.marks.add(mark)
            day.save()
        else:
            day = Day.objects.filter(day=current_date)[0]
            day.marks.add(mark)
            day.save()

        journal = Journal.objects.filter(to_user=MyUser.objects.filter(id=student_id)[0],
                                         lesson=Lesson_instance.objects.filter(id=lesson_id)[0])
        if len(journal) == 0 or journal is None:
            journal = Journal(to_user=MyUser.objects.filter(id=student_id)[0],
                              lesson=Lesson_instance.objects.filter(id=lesson_id)[0])
            journal.save()
            journal.days.add(day)
            journal.save()
        else:
            if not day in journal[0].days.all():
                journal[0].days.add(day)
                journal[0].save()
    return render(request, 'add_mark.html', context)


@login_required(login_url='/login')
def class_roster(request, class_n, class_a):
    context = dict()
    grade = Grade.objects.filter(grade_alpha=class_a, grade_number=class_n)[0]
    context['grade'] = grade
    context['head'] = grade.head
    context['roster'] = grade.get_roster()
    return render(request, 'class_roster.html', context)


@login_required(login_url='/login')
def my_schedule(request):
    context = dict()
    context['my_profile'] = True
    user = request.user
    if user.type_user == 2:
        my_grade = user.grade
        if user.schedule:
            faculty_week_sch = sorted(user.schedule.days(), key=lambda x: x.day)
        else:
            faculty_week_sch = list()
        if my_grade.schedule:
            grade_week_sch = sorted(my_grade.schedule.days(), key=lambda x: x.day)
        else:
            grade_week_sch = list()
        result = [list()] * 6

        for i in grade_week_sch:
            result[i.day - 1] = sorted(i.my_lessons(), key=lambda x: x.time)
        for i in faculty_week_sch:
            result[i.day - 1].extend(sorted(i.my_lessons(), key=lambda x: x.time))
        context['moday'] = result[0]
        context['tuday'] = result[1]
        context['weday'] = result[2]
        context['thday'] = result[3]
        context['frday'] = result[4]
        context['saday'] = result[5]

        for i in result:
            print(i)
            print()
    elif user.type_user == 1:
        result = [list()] * 6
        monday = DaySchedule.objects.filter(day=1)
        lessons_monday = []
        need_monday = []
        for i in monday:
            lessons_monday.extend(i.my_lessons())

        print(lessons_monday)
        for i in lessons_monday:
            if i.lecturer == user:
                need_monday.append(i)
        print(need_monday)
        result[0] = sorted(need_monday, key=lambda x: x.time)

        monday = DaySchedule.objects.filter(day=2)
        lessons_monday = []
        need_monday = []
        for i in monday:
            lessons_monday.extend(i.my_lessons())
        for i in lessons_monday:
            if i.lecturer == user:
                need_monday.append(i)
        result[1] = sorted(need_monday, key=lambda x: x.time)

        monday = DaySchedule.objects.filter(day=3)
        lessons_monday = []
        need_monday = []
        for i in monday:
            lessons_monday.extend(i.my_lessons())
        for i in lessons_monday:
            if i.lecturer == user:
                need_monday.append(i)
        result[2] = sorted(need_monday, key=lambda x: x.time)

        monday = DaySchedule.objects.filter(day=4)
        lessons_monday = []
        need_monday = []
        for i in monday:
            lessons_monday.extend(i.my_lessons())
        for i in lessons_monday:
            if i.lecturer == user:
                need_monday.append(i)
        result[3] = sorted(need_monday, key=lambda x: x.time)

        monday = DaySchedule.objects.filter(day=5)
        lessons_monday = []
        need_monday = []
        for i in monday:
            lessons_monday.extend(i.my_lessons())
        for i in lessons_monday:
            if i.lecturer == user:
                need_monday.append(i)
        result[4] = sorted(need_monday, key=lambda x: x.time)

        monday = DaySchedule.objects.filter(day=6)
        lessons_monday = []
        need_monday = []
        for i in monday:
            lessons_monday.extend(i.my_lessons())
        for i in lessons_monday:
            if i.lecturer == user:
                need_monday.append(i)
        result[5] = sorted(need_monday, key=lambda x: x.time)

        context['moday'] = result[0]
        context['tuday'] = result[1]
        context['weday'] = result[2]
        context['thday'] = result[3]
        context['frday'] = result[4]
        context['saday'] = result[5]
    return render(request, 'my_schedule.html', context)


@login_required(login_url='/login')
def foreigner_schedule(request, userid):
    context = dict()
    context['my_profile'] = False
    user = MyUser.objects.filter(id=userid)[0]
    context['touser'] = user
    if user.type_user == 2:
        my_grade = user.grade
        if my_grade:
            if user.schedule:
                faculty_week_sch = sorted(user.schedule.days(), key=lambda x: x.day)
            else:
                faculty_week_sch = list()
            if my_grade.schedule:
                grade_week_sch = sorted(my_grade.schedule.days(), key=lambda x: x.day)
            else:
                grade_week_sch = list()
            result = [list()] * 6

            for i in grade_week_sch:
                result[i.day - 1] = sorted(i.my_lessons(), key=lambda x: x.time)
            for i in faculty_week_sch:
                result[i.day - 1].extend(sorted(i.my_lessons(), key=lambda x: x.time))
            context['moday'] = result[0]
            context['tuday'] = result[1]
            context['weday'] = result[2]
            context['thday'] = result[3]
            context['frday'] = result[4]
            context['saday'] = result[5]

            for i in result:
                print(i)
                print()
    elif user.type_user == 1:
        result = [list()] * 6
        monday = DaySchedule.objects.filter(day=1)
        lessons_monday = []
        need_monday = []
        for i in monday:
            lessons_monday.extend(i.my_lessons())
        for i in lessons_monday:
            if i.lecturer == user:
                need_monday.append(i)
        result[0] = sorted(need_monday, key=lambda x: x.time)

        monday = DaySchedule.objects.filter(day=2)
        lessons_monday = []
        need_monday = []
        for i in monday:
            lessons_monday.extend(i.my_lessons())
        for i in lessons_monday:
            if i.lecturer == user:
                need_monday.append(i)
        result[1] = sorted(need_monday, key=lambda x: x.time)

        monday = DaySchedule.objects.filter(day=3)
        lessons_monday = []
        need_monday = []
        for i in monday:
            lessons_monday.extend(i.my_lessons())
        for i in lessons_monday:
            if i.lecturer == user:
                need_monday.append(i)
        result[2] = sorted(need_monday, key=lambda x: x.time)

        monday = DaySchedule.objects.filter(day=4)
        lessons_monday = []
        need_monday = []
        for i in monday:
            lessons_monday.extend(i.my_lessons())
        for i in lessons_monday:
            if i.lecturer == user:
                need_monday.append(i)
        result[3] = sorted(need_monday, key=lambda x: x.time)

        monday = DaySchedule.objects.filter(day=5)
        lessons_monday = []
        need_monday = []
        for i in monday:
            lessons_monday.extend(i.my_lessons())
        for i in lessons_monday:
            if i.lecturer == user:
                need_monday.append(i)
        result[4] = sorted(need_monday, key=lambda x: x.time)

        monday = DaySchedule.objects.filter(day=6)
        lessons_monday = []
        need_monday = []
        for i in monday:
            lessons_monday.extend(i.my_lessons())
        for i in lessons_monday:
            if i.lecturer == user:
                need_monday.append(i)
        result[5] = sorted(need_monday, key=lambda x: x.time)

        context['moday'] = result[0]
        context['tuday'] = result[1]
        context['weday'] = result[2]
        context['thday'] = result[3]
        context['frday'] = result[4]
        context['saday'] = result[5]

    return render(request, 'my_schedule.html', context)


@login_required(login_url='/login')
def class_info(request, class_n, class_a):
    context = dict()
    user = request.user

ezh/journal/templates/add_mark.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Добавить оценку</title>
</head>
<body>
    <form method="POST">
        {%csrf_token%}
        <input type="text" name="mark" placeholder="Оценка 2-5">
        <input type="text" name="lesson_id" placeholder="id lesson">
        <input type="text" name="student_id" placeholder="id student">
        <input type="submit" value="Go!">
    </form>
</body>
</html>

ezh/journal/templates/class_roster.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Список класса</title>
    {% include "includes/head_includes.html"%}
</head>

<body>
<div class="wrapper">
    <header>
    {% include "includes/navbar.html"%}
  </header>
    <div class="container">
        <div class="form-title">
            <hr>
            <h1>Список класса <span style="color:grey">{{grade.grade_number}}{{grade.grade_alpha}}</span></h1>
            <hr>
        </div>
        {% if head %}
        <div class="form-group">
            <h3>Классный руководитель</h3>
        </div>
        <div class="table-responsive">
        <table class="table">
            <tbody>
            <thead class="thead-dark">
            <tr>
                <th>Логин</th>
                <th>Имя</th>
                <th>Фамилия</th>
                <th>Отчество</th>
                <th>Предмет</th>
                <th>Телефон</th>
                <th>Статус</th>
            </tr>
            </thead>
            <tr>
                <td><a href="{% url 'journal:foreigner_profile' head.id%}">{{head.username}}</a></td>
                <td>{{head.first_name}}</td>
                <td>{{head.last_name}}</td>
                <td>{{head.midname}}</td>
                <td>{{head.to_teach}}</td>
                <td>{{head.telephone}}</td>
                <td>{%if head.activated%} <span style="color:green">Активирован </span>{%else%}<span style="color:red"> Не активирован </span> {%endif%}</td>
            </tr>
            </tbody>
        </table>
        </div>
        <br>
        <br>
        {%endif%}
        {%if roster%}
        <h3>Ученики</h3>
        <div class="table-responsive">
        <table class="table">
            <tbody>
            <thead class="thead-dark">
            <tr>
                <th>Логин</th>
                <th>Имя</th>
                <th>Фамилия</th>
                <th>Отчество</th>
                <th>Телефон</th>
                <th>Статус</th>
            </tr>
            </thead>
            {%for i in roster%}
            <tr>
                <td><a href="{% url 'journal:foreigner_profile' i.id%}">{%if i.activated %}{{i.username}}{%else%}Нет логина{%endif%}</a></td>
                <td>{{i.first_name}}</td>
                <td>{{i.last_name}}</td>
                <td>{{i.midname}}</td>
                <td>{{i.telephone}}</td>
                <td>{%if i.activated%} <span style="color:green">Активирован </span>{%else%}<span style="color:red"> Не активирован </span>{%endif%}</td>
            </tr>
            {%endfor%}
            </tbody>
        </table>
        </div>
        {%endif%}
    </div>

</div>
</body>
</html>

ezh/journal/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Профиль</title>
    {% include "includes/head_includes.html"%}
    <style>
        .user-section{
            margin-top: 50px;
        }
        .userdata{
            /*border: solid 1px black;
            padding: 3px 0;*/
            font-size: 1.1em;
            display: flex;
            
        }
        .userparam{
            display: inline-block;
            width: 40%;
        }
        .userparam-data{
            display: inline-block;
            width: 40%;
        }
    </style>
    {% include "includes/head_includes.html"%}
</head>

<body>
    
    <header>
        {% include "includes/navbar.html"%}
    </header>

    <div class="wrapper">
    <div class="container">
        <div class="form-title">
            <hr>
            {%if my_profile%}
            <h1>Мой профиль</h1>
            {%else%}
            <h1>Профиль <span style="color:grey">{{touser.first_name}} {{touser.last_name}}</span></h1>
            {%endif%}
            <hr>
            <p></p>
        </div>

    <section class="user-section">
        {%if touser.activated%}
        <div class="userdata"><div class="userparam">Логин: </div>          <div class="userparam-data">{{touser.username}}</div> </div>
        <p style="color:green">Профиль активирован</p>
        {%else%}
        <p style="color:red">Профиль не активирован</p>
        {%endif%}
        <hr >
        <div class="userdata"><div class="userparam">Имя: </div>            <div class="userparam-data"> {{touser.first_name}}</div></div>
        <hr>   
        <div class="userdata"><div class="userparam">Фамилия: </div>        <div class="userparam-data">{{touser.last_name}}</div> </div>
        <hr>
        <div class="userdata"><div class="userparam">Отчество: </div>       <div class="userparam-data">{{touser.midname}}</div> </div>
        <hr>
        <div class="userdata"><div class="userparam">Почта: </div>          <div class="userparam-data"> {{touser.email}}</div></div>
        <hr>
        <div class="userdata"><div class="userparam">Дата рождения: </div>  <div class="userparam-data"> {{touser.date_of_birth}}</div></div>
        <hr>
        <div class="userdata"><div class="userparam">Телефон: </div>        <div class="userparam-data"> {{touser.telephone}}</div></div>
        <hr>
        <div class="userdata"><div class="userparam">Должность: </div>      <div class="userparam-data">{{userrole}}</div> </div>
        <hr>
        <div class="userdata"><div class="userparam">Информация о родителях: </div>      <div class="userparam-data">{{touser.info_parents}}</div> </div>
        <hr>
        {% if touser.type_user == 1 %}
        <div class="userdata"><div class="userparam">Руководитель: </div>      <div class="userparam-data">{% autoescape off %}{{touser.show_self_grades}}{% endautoescape %}</div> </div>
        {%endif%}
        {%if my_profile%}
        <a name='edit' href="{% url 'journal:profile_edit' %}" class="btn-primary btn btn-form" style="color:white">Редактировать профиль</a>
        <br>
        <br>
        <form method="POST">
            {% csrf_token %}
        <input type="submit" value="Выйти" name='logout' class="btn-danger btn btn-form">
        </form>
        {%endif%}

        {% if touser.type_user == 2 %}
        <div class="userdata">Класс обучения:  <a href ="{% url 'journal:class_roster' touser.grade.grade_number touser.grade.grade_alpha%}" > {{user.grade.grade_number}}{{user.grade.grade_alpha}}</a></div>
        <a href="{% url 'journal:foreigner_marks' touser.id%}">Посмотреть успеваемость</a>
        {%endif%}
        <br>
        {%if my_profile%}
        <a href="{% url 'journal:my_schedule'%}">Показать расписание</a>
        {%else%}
        <a href="{% url 'journal:foreigner_schedule' touser.id%}">Показать расписание</a>
        {%endif%}
        {% if touser.type_user == 3 %}
        <div class="userdata">Выполняет работу: {{touser.staff_role}}</div>
        {%endif%}

    </section>

    </div>
    </div>
</body>
</html>

ezh/journal/templates/profile_edit.html
<!DOCTYPE html>
<html lang="en">
<head>

    <title>Редактирование профиля</title>
     {% include "includes/head_includes.html"%}
</head>

<body>
<header>
    {% include "includes/navbar.html"%}
  </header>
    <div class="wrapper">
        <div class="container">
            <div class="form-title">
                <hr>
                <h1>Редактирование профиля <span style="color:grey">{{user.first_name}} {{user.last_name}}</span></h1>
                <hr>
            </div>

            <form method="POST">
            {% csrf_token %}
                <div class="form-group">
                    <h5>Ваш номер телефона</h5>
                    <input type="tel" class="form-control" value="{{user.telephone}}" placeholder="Телефонный номер" name="telephone">
                    <p style="color:grey">Вводите, начиная с 8, без дополнительных знаков и разделителей</p>
                </div>
                <div class="form-group">
                    <h5>Ваш email</h5>
                    <input type="email" value="{{user.email}}" class="form-control" placeholder="Электронная почта" name="email">
                </div>
                {%if user.type_user == 3%}
                <div class="form-group">
                    <h5>Ваши компетенции</h5>
                    <input type="text" class="form-control" placeholder="Перечислите список ваших компетенций" name="staff_role">
                </div>
                {%endif%}
                <input type="submit" value="Сохранить изменения" name='enter' class="btn-primary btn btn-form">
                <a name='cancel' href="{% url 'journal:profile' %}" class="btn-danger btn btn-form" style="color:white">Отменить изменения</a>
            </form>
        </div>
    </div>






</body>
</html>

ezh/journal/templates/school_roster.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Список школы</title>
    {% include "includes/head_includes.html"%}
</head>

<body>

    <header>
        {% include "includes/navbar.html"%}
    </header>

    <div class="wrapper">
        <div class="container">
            <div class="form-title">
                <hr>
                <h1>Список школы</h1>
                <hr>
            </div>
            <div class="form-group">
                <h3>Учителя</h3>
            </div>
            <div class="table-responsive">
            <table class="table">
                <tbody>
                    <thead class="thead-dark">
                        <tr>
                            <th>Логин</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Отчество</th>
                            <th>Предмет</th>
                            <th>Телефон</th>
                            <th>К.рук</th>
                            <th>Статус</th>
                        </tr>
                    </thead>
                    {%for i in teachers%}
                    <tr>
                        <td><a href="{% url 'journal:foreigner_profile' i.id%}">{%if i.activated %}{{i.username}}{%else%}Нет
                                логина{%endif%}</a></td>
                        <td>{{i.first_name}}</td>
                        <td>{{i.last_name}}</td>
                        <td>{{i.midname}}</td>
                        <td>{{i.to_teach}}</td>
                        <td>{{i.telephone}}</td>
                        <td>{% autoescape off %}{{i.show_self_grades}}{%endautoescape%}</td>
                        <td>{%if i.activated%} <span style="color:green">Активирован </span>{%else%}<span
                                style="color:red"> Не активирован </span>{%endif%}</td>
                    </tr>
                    {%endfor%}
                </tbody>
            </table>
            </div>
            <br>
            <br>
            <h3>Ученики</h3>
            <div class="table-responsive">
            <table class="table">
                <tbody>
                    <thead class="thead-dark">
                        <tr>
                            <th>Логин</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Отчество</th>
                            <th>Класс</th>
                            <th>Телефон</th>
                            <th>Статус</th>
                        </tr>
                    </thead>
                    {%for i in students%}
                    <tr>
                        <td><a href="{% url 'journal:foreigner_profile' i.id%}">{%if i.activated %}{{i.username}}{%else%}Нет
                                логина{%endif%}</a></td>
                        <td>{{i.first_name}}</td>
                        <td>{{i.last_name}}</td>
                        <td>{{i.midname}}</td>
                        <td><a
                                href="{% url 'journal:class_info' i.grade.grade_number i.grade.grade_alpha%}">{{i.grade.grade_number}}{{i.grade.grade_alpha}}</a>
                        </td>
                        <td>{{i.telephone}}</td>
                        <td>{%if i.activated%} <span style="color:green">Активирован </span>{%else%}<span
                                style="color:red"> Не активирован </span>{%endif%}</td>
                    </tr>
                    {%endfor%}
                </tbody>
            </table>
            </div>
            <br>
            <br>
            <h3>Стафф</h3>
            <div class="table-responsive">
            <table class="table">
                <tbody>
                    <thead class="thead-dark">
                        <tr>
                            <th>Логин</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Отчество</th>
                            <th>Должность</th>
                            <th>Телефон</th>
                            <th>Статус</th>
                        </tr>
                    </thead>
                    {%for i in staff%}
                    <tr>
                        <td><a href="{% url 'journal:foreigner_profile' i.id%}">{%if i.activated %}{{i.username}}{%else%}Нет
                                логина{%endif%}</a></td>
                        <td>{{i.first_name}}</td>
                        <td>{{i.last_name}}</td>
                        <td>{{i.midname}}</td>
                        <td>{{i.staff_role}}</td>
                        <td>{{i.telephone}}</td>
                        <td>{%if i.activated%} <span style="color:green">Активирован </span>{%else%}<span
                                style="color:red"> Не активирован </span>{%endif%}</td>
                    </tr>
                    {%endfor%}
                </tbody>
            </table>
            </div>
        </div>

    </div>
</body>

</html>